{
 "title": "MicroServices Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_cpu_user_seconds_total", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Messages Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "microservices_messages_received_total",
     "legendFormat": "{{service}} - {{type}}"
    }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "microservices_messages_sent_total",
     "legendFormat": "{{service}} - {{type}}"
    }
   ]
  },
  {
   "title": "Job Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "microservices_job_processing_seconds",
     "legendFormat": "{{service}} - {{job_type}}"
    }
   ]
  },
  {
   "title": "Number of Workers by Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "microservices_workers_total", "legendFormat": "{{type}}" }
   ]
  }
 ]
}